name: photo_albums
description: "Desafio A&3"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  dio: ^5.4.0
  signals: ^6.0.2
  signals_flutter: ^6.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  url_launcher: ^6.2.6
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

